### ISSUE TITLE
STREAM Memory Leak

### ISSUE THREAD

**Issue by ekrenzke** [emschwartz/ilp-rs#13]
After a brief discussion with Evan, there appears to be a small memory leak in the current implementation.

> When the connection closes, it leaves one future hanging on the client side, and at least one future hanging on the server side. It might be the result of splitting the plug-in into channels.

**Tasks**
- [ ] Reproduce the issue.
- [ ] Confirm/deny the issue is the result of channel usage.

**Comment by emschwartz** [comment]
This issue was addressed by https://github.com/emschwartz/ilp-rs/commit/4c508d6948e151d6bc55a54cb6709a8add1f1988
